export type Country = {
  code: string
  name_pt: string
  name_es: string
  name_en: string
  dial: string
  flag: string
  /** Idioma del país cuando es portugués o español; en el resto manda el idioma de quien usa la app. */
  lang?: 'pt' | 'es'
  currency: string
  mask: string
  digits: number
  pix: boolean
}

export const COUNTRIES: Country[] = [
  { code: 'BR', name_pt: 'Brasil', name_es: 'Brasil', name_en: 'Brazil', dial: '+55', flag: '🇧🇷', lang: 'pt', currency: 'BRL', mask: 'DD 9 XXXX XXXX', digits: 11, pix: true },
  { code: 'PT', name_pt: 'Portugal', name_es: 'Portugal', name_en: 'Portugal', dial: '+351', flag: '🇵🇹', lang: 'pt', currency: 'EUR', mask: 'DDD XXX XXX', digits: 9, pix: false },
  { code: 'ES', name_pt: 'Espanha', name_es: 'España', name_en: 'Spain', dial: '+34', flag: '🇪🇸', lang: 'es', currency: 'EUR', mask: 'DDD XX XX XX', digits: 9, pix: false },
  { code: 'UY', name_pt: 'Uruguai', name_es: 'Uruguay', name_en: 'Uruguay', dial: '+598', flag: '🇺🇾', lang: 'es', currency: 'UYU', mask: 'DD XXX XXX', digits: 8, pix: false },
  { code: 'AR', name_pt: 'Argentina', name_es: 'Argentina', name_en: 'Argentina', dial: '+54', flag: '🇦🇷', lang: 'es', currency: 'ARS', mask: 'DDD XXXX XXXX', digits: 10, pix: false },
  { code: 'BO', name_pt: 'Bolívia', name_es: 'Bolivia', name_en: 'Bolivia', dial: '+591', flag: '🇧🇴', lang: 'es', currency: 'BOB', mask: 'DDDD DDDD', digits: 8, pix: false },
  { code: 'PY', name_pt: 'Paraguai', name_es: 'Paraguay', name_en: 'Paraguay', dial: '+595', flag: '🇵🇾', lang: 'es', currency: 'PYG', mask: 'DDD XXX XXX', digits: 9, pix: false },
  { code: 'CL', name_pt: 'Chile', name_es: 'Chile', name_en: 'Chile', dial: '+56', flag: '🇨🇱', lang: 'es', currency: 'CLP', mask: 'D XXXX XXXX', digits: 9, pix: false },
  { code: 'CO', name_pt: 'Colômbia', name_es: 'Colombia', name_en: 'Colombia', dial: '+57', flag: '🇨🇴', lang: 'es', currency: 'COP', mask: 'DDD XXX XXXX', digits: 10, pix: false },
  { code: 'PE', name_pt: 'Peru', name_es: 'Perú', name_en: 'Peru', dial: '+51', flag: '🇵🇪', lang: 'es', currency: 'PEN', mask: 'DDD DDD DDD', digits: 9, pix: false },
  { code: 'EC', name_pt: 'Equador', name_es: 'Ecuador', name_en: 'Ecuador', dial: '+593', flag: '🇪🇨', lang: 'es', currency: 'USD', mask: 'DD XXX XXXX', digits: 9, pix: false },
  { code: 'VE', name_pt: 'Venezuela', name_es: 'Venezuela', name_en: 'Venezuela', dial: '+58', flag: '🇻🇪', lang: 'es', currency: 'USD', mask: 'DDD XXX XXXX', digits: 10, pix: false },
  // Resto del mundo (generado: prefijos y largos de libphonenumber, nombres de Intl.DisplayNames).
  { code: 'AD', name_pt: 'Andorra', name_es: 'Andorra', name_en: 'Andorra', dial: '+376', flag: '🇦🇩', currency: 'EUR', mask: 'XXX XXX', digits: 9, pix: false },
  { code: 'AE', name_pt: 'Emirados Árabes Unidos', name_es: 'Emiratos Árabes Unidos', name_en: 'United Arab Emirates', dial: '+971', flag: '🇦🇪', currency: 'AED', mask: 'XX XXX XXXX', digits: 12, pix: false },
  { code: 'AF', name_pt: 'Afeganistão', name_es: 'Afganistán', name_en: 'Afghanistan', dial: '+93', flag: '🇦🇫', currency: 'AFN', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'AG', name_pt: 'Antígua e Barbuda', name_es: 'Antigua y Barbuda', name_en: 'Antigua & Barbuda', dial: '+1', flag: '🇦🇬', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'AI', name_pt: 'Anguila', name_es: 'Anguila', name_en: 'Anguilla', dial: '+1', flag: '🇦🇮', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'AL', name_pt: 'Albânia', name_es: 'Albania', name_en: 'Albania', dial: '+355', flag: '🇦🇱', currency: 'ALL', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'AM', name_pt: 'Armênia', name_es: 'Armenia', name_en: 'Armenia', dial: '+374', flag: '🇦🇲', currency: 'AMD', mask: 'XX XXXXXX', digits: 8, pix: false },
  { code: 'AO', name_pt: 'Angola', name_es: 'Angola', name_en: 'Angola', dial: '+244', flag: '🇦🇴', lang: 'pt', currency: 'AOA', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'AS', name_pt: 'Samoa Americana', name_es: 'Samoa Americana', name_en: 'American Samoa', dial: '+1', flag: '🇦🇸', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'AT', name_pt: 'Áustria', name_es: 'Austria', name_en: 'Austria', dial: '+43', flag: '🇦🇹', currency: 'EUR', mask: 'XXX XXXXXX', digits: 13, pix: false },
  { code: 'AU', name_pt: 'Austrália', name_es: 'Australia', name_en: 'Australia', dial: '+61', flag: '🇦🇺', currency: 'AUD', mask: 'XXX XXX XXX', digits: 12, pix: false },
  { code: 'AW', name_pt: 'Aruba', name_es: 'Aruba', name_en: 'Aruba', dial: '+297', flag: '🇦🇼', currency: 'AWG', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'AX', name_pt: 'Ilhas Aland', name_es: 'Islas Åland', name_en: 'Åland Islands', dial: '+358', flag: '🇦🇽', currency: 'EUR', mask: 'XX XXXXXXX', digits: 12, pix: false },
  { code: 'AZ', name_pt: 'Azerbaijão', name_es: 'Azerbaiyán', name_en: 'Azerbaijan', dial: '+994', flag: '🇦🇿', currency: 'AZN', mask: 'XX XXX XX XX', digits: 9, pix: false },
  { code: 'BA', name_pt: 'Bósnia e Herzegovina', name_es: 'Bosnia-Herzegovina', name_en: 'Bosnia & Herzegovina', dial: '+387', flag: '🇧🇦', currency: 'BAM', mask: 'XX XXX XXX', digits: 9, pix: false },
  { code: 'BB', name_pt: 'Barbados', name_es: 'Barbados', name_en: 'Barbados', dial: '+1', flag: '🇧🇧', currency: 'BBD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'BD', name_pt: 'Bangladesh', name_es: 'Bangladés', name_en: 'Bangladesh', dial: '+880', flag: '🇧🇩', currency: 'BDT', mask: 'XXXX XXXXXX', digits: 10, pix: false },
  { code: 'BE', name_pt: 'Bélgica', name_es: 'Bélgica', name_en: 'Belgium', dial: '+32', flag: '🇧🇪', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'BF', name_pt: 'Burquina Faso', name_es: 'Burkina Faso', name_en: 'Burkina Faso', dial: '+226', flag: '🇧🇫', currency: 'XOF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'BG', name_pt: 'Bulgária', name_es: 'Bulgaria', name_en: 'Bulgaria', dial: '+359', flag: '🇧🇬', currency: 'EUR', mask: 'XX XXX XXX', digits: 12, pix: false },
  { code: 'BH', name_pt: 'Barein', name_es: 'Baréin', name_en: 'Bahrain', dial: '+973', flag: '🇧🇭', currency: 'BHD', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'BI', name_pt: 'Burundi', name_es: 'Burundi', name_en: 'Burundi', dial: '+257', flag: '🇧🇮', currency: 'BIF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'BJ', name_pt: 'Benin', name_es: 'Benín', name_en: 'Benin', dial: '+229', flag: '🇧🇯', currency: 'XOF', mask: 'X XX XX XX XX', digits: 10, pix: false },
  { code: 'BL', name_pt: 'São Bartolomeu', name_es: 'San Bartolomé', name_en: 'St. Barthélemy', dial: '+590', flag: '🇧🇱', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'BM', name_pt: 'Bermudas', name_es: 'Bermudas', name_en: 'Bermuda', dial: '+1', flag: '🇧🇲', currency: 'BMD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'BN', name_pt: 'Brunei', name_es: 'Brunéi', name_en: 'Brunei', dial: '+673', flag: '🇧🇳', currency: 'BND', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'BQ', name_pt: 'Países Baixos Caribenhos', name_es: 'Caribe neerlandés', name_en: 'Caribbean Netherlands', dial: '+599', flag: '🇧🇶', currency: 'USD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'BS', name_pt: 'Bahamas', name_es: 'Bahamas', name_en: 'Bahamas', dial: '+1', flag: '🇧🇸', currency: 'BSD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'BT', name_pt: 'Butão', name_es: 'Bután', name_en: 'Bhutan', dial: '+975', flag: '🇧🇹', currency: 'BTN', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'BW', name_pt: 'Botsuana', name_es: 'Botsuana', name_en: 'Botswana', dial: '+267', flag: '🇧🇼', currency: 'BWP', mask: 'XX XXX XXX', digits: 10, pix: false },
  { code: 'BY', name_pt: 'Bielorrússia', name_es: 'Bielorrusia', name_en: 'Belarus', dial: '+375', flag: '🇧🇾', currency: 'BYN', mask: 'X XXX XXX XX XX', digits: 11, pix: false },
  { code: 'BZ', name_pt: 'Belize', name_es: 'Belice', name_en: 'Belize', dial: '+501', flag: '🇧🇿', currency: 'BZD', mask: 'XXX XXXX', digits: 11, pix: false },
  { code: 'CA', name_pt: 'Canadá', name_es: 'Canadá', name_en: 'Canada', dial: '+1', flag: '🇨🇦', currency: 'CAD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'CC', name_pt: 'Ilhas Cocos (Keeling)', name_es: 'Islas Cocos', name_en: 'Cocos (Keeling) Islands', dial: '+61', flag: '🇨🇨', currency: 'AUD', mask: 'XXX XXX XXX', digits: 12, pix: false },
  { code: 'CD', name_pt: 'Congo - Kinshasa', name_es: 'República Democrática del Congo', name_en: 'Congo - Kinshasa', dial: '+243', flag: '🇨🇩', currency: 'CDF', mask: 'XXX XXX XXX', digits: 10, pix: false },
  { code: 'CF', name_pt: 'República Centro-Africana', name_es: 'República Centroafricana', name_en: 'Central African Republic', dial: '+236', flag: '🇨🇫', currency: 'XAF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'CG', name_pt: 'República do Congo', name_es: 'República del Congo', name_en: 'Congo - Brazzaville', dial: '+242', flag: '🇨🇬', currency: 'XAF', mask: 'X XXX XXXX', digits: 9, pix: false },
  { code: 'CH', name_pt: 'Suíça', name_es: 'Suiza', name_en: 'Switzerland', dial: '+41', flag: '🇨🇭', currency: 'CHF', mask: 'XX XXX XX XX', digits: 12, pix: false },
  { code: 'CI', name_pt: 'Costa do Marfim', name_es: 'Costa de Marfil', name_en: 'Côte d’Ivoire', dial: '+225', flag: '🇨🇮', currency: 'XOF', mask: 'X XX XX XXXX', digits: 10, pix: false },
  { code: 'CK', name_pt: 'Ilhas Cook', name_es: 'Islas Cook', name_en: 'Cook Islands', dial: '+682', flag: '🇨🇰', currency: 'NZD', mask: 'XX XXX', digits: 5, pix: false },
  { code: 'CM', name_pt: 'Camarões', name_es: 'Camerún', name_en: 'Cameroon', dial: '+237', flag: '🇨🇲', currency: 'XAF', mask: 'X XX XX XX XX', digits: 9, pix: false },
  { code: 'CN', name_pt: 'China', name_es: 'China', name_en: 'China', dial: '+86', flag: '🇨🇳', currency: 'CNY', mask: 'XXX XXXX XXXX', digits: 12, pix: false },
  { code: 'CR', name_pt: 'Costa Rica', name_es: 'Costa Rica', name_en: 'Costa Rica', dial: '+506', flag: '🇨🇷', lang: 'es', currency: 'CRC', mask: 'XXXX XXXX', digits: 10, pix: false },
  { code: 'CU', name_pt: 'Cuba', name_es: 'Cuba', name_en: 'Cuba', dial: '+53', flag: '🇨🇺', lang: 'es', currency: 'CUP', mask: 'X XXXXXXX', digits: 10, pix: false },
  { code: 'CV', name_pt: 'Cabo Verde', name_es: 'Cabo Verde', name_en: 'Cape Verde', dial: '+238', flag: '🇨🇻', lang: 'pt', currency: 'CVE', mask: 'XXX XX XX', digits: 7, pix: false },
  { code: 'CW', name_pt: 'Curaçao', name_es: 'Curazao', name_en: 'Curaçao', dial: '+599', flag: '🇨🇼', currency: 'XCG', mask: 'X XXX XXXX', digits: 8, pix: false },
  { code: 'CX', name_pt: 'Ilha Christmas', name_es: 'Isla de Navidad', name_en: 'Christmas Island', dial: '+61', flag: '🇨🇽', currency: 'AUD', mask: 'XXX XXX XXX', digits: 12, pix: false },
  { code: 'CY', name_pt: 'Chipre', name_es: 'Chipre', name_en: 'Cyprus', dial: '+357', flag: '🇨🇾', currency: 'EUR', mask: 'XX XXXXXX', digits: 8, pix: false },
  { code: 'CZ', name_pt: 'Tchéquia', name_es: 'Chequia', name_en: 'Czechia', dial: '+420', flag: '🇨🇿', currency: 'CZK', mask: 'XXX XXX XXX', digits: 12, pix: false },
  { code: 'DE', name_pt: 'Alemanha', name_es: 'Alemania', name_en: 'Germany', dial: '+49', flag: '🇩🇪', currency: 'EUR', mask: 'XXXX XXXXXXX', digits: 15, pix: false },
  { code: 'DJ', name_pt: 'Djibuti', name_es: 'Yibuti', name_en: 'Djibouti', dial: '+253', flag: '🇩🇯', currency: 'DJF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'DK', name_pt: 'Dinamarca', name_es: 'Dinamarca', name_en: 'Denmark', dial: '+45', flag: '🇩🇰', currency: 'DKK', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'DM', name_pt: 'Dominica', name_es: 'Dominica', name_en: 'Dominica', dial: '+1', flag: '🇩🇲', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'DO', name_pt: 'República Dominicana', name_es: 'República Dominicana', name_en: 'Dominican Republic', dial: '+1', flag: '🇩🇴', lang: 'es', currency: 'DOP', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'DZ', name_pt: 'Argélia', name_es: 'Argelia', name_en: 'Algeria', dial: '+213', flag: '🇩🇿', currency: 'DZD', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'EE', name_pt: 'Estônia', name_es: 'Estonia', name_en: 'Estonia', dial: '+372', flag: '🇪🇪', currency: 'EUR', mask: 'XXXX XXXX', digits: 10, pix: false },
  { code: 'EG', name_pt: 'Egito', name_es: 'Egipto', name_en: 'Egypt', dial: '+20', flag: '🇪🇬', currency: 'EGP', mask: 'XX XXXXXXXX', digits: 10, pix: false },
  { code: 'EH', name_pt: 'Saara Ocidental', name_es: 'Sáhara Occidental', name_en: 'Western Sahara', dial: '+212', flag: '🇪🇭', currency: 'MAD', mask: 'X XX XX XX XX', digits: 9, pix: false },
  { code: 'ER', name_pt: 'Eritreia', name_es: 'Eritrea', name_en: 'Eritrea', dial: '+291', flag: '🇪🇷', currency: 'ERN', mask: 'X XXX XXX', digits: 7, pix: false },
  { code: 'ET', name_pt: 'Etiópia', name_es: 'Etiopía', name_en: 'Ethiopia', dial: '+251', flag: '🇪🇹', currency: 'ETB', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'FI', name_pt: 'Finlândia', name_es: 'Finlandia', name_en: 'Finland', dial: '+358', flag: '🇫🇮', currency: 'EUR', mask: 'XX XXXXXXX', digits: 12, pix: false },
  { code: 'FJ', name_pt: 'Fiji', name_es: 'Fiyi', name_en: 'Fiji', dial: '+679', flag: '🇫🇯', currency: 'FJD', mask: 'XXX XXXX', digits: 11, pix: false },
  { code: 'FK', name_pt: 'Ilhas Malvinas', name_es: 'Islas Malvinas', name_en: 'Falkland Islands', dial: '+500', flag: '🇫🇰', currency: 'FKP', mask: 'XXXXX', digits: 5, pix: false },
  { code: 'FM', name_pt: 'Micronésia', name_es: 'Micronesia', name_en: 'Micronesia', dial: '+691', flag: '🇫🇲', currency: 'USD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'FO', name_pt: 'Ilhas Faroé', name_es: 'Islas Feroe', name_en: 'Faroe Islands', dial: '+298', flag: '🇫🇴', currency: 'DKK', mask: 'XX XX XX', digits: 6, pix: false },
  { code: 'FR', name_pt: 'França', name_es: 'Francia', name_en: 'France', dial: '+33', flag: '🇫🇷', currency: 'EUR', mask: 'X XX XX XX XX', digits: 9, pix: false },
  { code: 'GA', name_pt: 'Gabão', name_es: 'Gabón', name_en: 'Gabon', dial: '+241', flag: '🇬🇦', currency: 'XAF', mask: 'X XX XX XX', digits: 8, pix: false },
  { code: 'GB', name_pt: 'Reino Unido', name_es: 'Reino Unido', name_en: 'United Kingdom', dial: '+44', flag: '🇬🇧', currency: 'GBP', mask: 'XXXX XXXXXX', digits: 10, pix: false },
  { code: 'GD', name_pt: 'Granada', name_es: 'Granada', name_en: 'Grenada', dial: '+1', flag: '🇬🇩', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'GE', name_pt: 'Geórgia', name_es: 'Georgia', name_en: 'Georgia', dial: '+995', flag: '🇬🇪', currency: 'GEL', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'GF', name_pt: 'Guiana Francesa', name_es: 'Guayana Francesa', name_en: 'French Guiana', dial: '+594', flag: '🇬🇫', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'GG', name_pt: 'Guernsey', name_es: 'Guernesey', name_en: 'Guernsey', dial: '+44', flag: '🇬🇬', currency: 'GBP', mask: 'XXXX XXXXXX', digits: 10, pix: false },
  { code: 'GH', name_pt: 'Gana', name_es: 'Ghana', name_en: 'Ghana', dial: '+233', flag: '🇬🇭', currency: 'GHS', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'GI', name_pt: 'Gibraltar', name_es: 'Gibraltar', name_en: 'Gibraltar', dial: '+350', flag: '🇬🇮', currency: 'GIP', mask: 'XXXXXXXX', digits: 8, pix: false },
  { code: 'GL', name_pt: 'Groenlândia', name_es: 'Groenlandia', name_en: 'Greenland', dial: '+299', flag: '🇬🇱', currency: 'DKK', mask: 'XX XX XX', digits: 6, pix: false },
  { code: 'GM', name_pt: 'Gâmbia', name_es: 'Gambia', name_en: 'Gambia', dial: '+220', flag: '🇬🇲', currency: 'GMD', mask: 'XXX XXXX', digits: 9, pix: false },
  { code: 'GN', name_pt: 'Guiné', name_es: 'Guinea', name_en: 'Guinea', dial: '+224', flag: '🇬🇳', currency: 'GNF', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'GP', name_pt: 'Guadalupe', name_es: 'Guadalupe', name_en: 'Guadeloupe', dial: '+590', flag: '🇬🇵', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'GQ', name_pt: 'Guiné Equatorial', name_es: 'Guinea Ecuatorial', name_en: 'Equatorial Guinea', dial: '+240', flag: '🇬🇶', lang: 'es', currency: 'XAF', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'GR', name_pt: 'Grécia', name_es: 'Grecia', name_en: 'Greece', dial: '+30', flag: '🇬🇷', currency: 'EUR', mask: 'XXX XXX XXXX', digits: 12, pix: false },
  { code: 'GT', name_pt: 'Guatemala', name_es: 'Guatemala', name_en: 'Guatemala', dial: '+502', flag: '🇬🇹', lang: 'es', currency: 'GTQ', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'GU', name_pt: 'Guam', name_es: 'Guam', name_en: 'Guam', dial: '+1', flag: '🇬🇺', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'GW', name_pt: 'Guiné-Bissau', name_es: 'Guinea-Bisáu', name_en: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼', lang: 'pt', currency: 'XOF', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'GY', name_pt: 'Guiana', name_es: 'Guyana', name_en: 'Guyana', dial: '+592', flag: '🇬🇾', currency: 'GYD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'HK', name_pt: 'Hong Kong, RAE da China', name_es: 'RAE de Hong Kong (China)', name_en: 'Hong Kong SAR China', dial: '+852', flag: '🇭🇰', currency: 'HKD', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'HN', name_pt: 'Honduras', name_es: 'Honduras', name_en: 'Honduras', dial: '+504', flag: '🇭🇳', lang: 'es', currency: 'HNL', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'HR', name_pt: 'Croácia', name_es: 'Croacia', name_en: 'Croatia', dial: '+385', flag: '🇭🇷', currency: 'EUR', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'HT', name_pt: 'Haiti', name_es: 'Haití', name_en: 'Haiti', dial: '+509', flag: '🇭🇹', currency: 'HTG', mask: 'XX XX XXXX', digits: 8, pix: false },
  { code: 'HU', name_pt: 'Hungria', name_es: 'Hungría', name_en: 'Hungary', dial: '+36', flag: '🇭🇺', currency: 'HUF', mask: 'X XX XXX XXXX', digits: 9, pix: false },
  { code: 'ID', name_pt: 'Indonésia', name_es: 'Indonesia', name_en: 'Indonesia', dial: '+62', flag: '🇮🇩', currency: 'IDR', mask: 'XXX XXX XXX', digits: 15, pix: false },
  { code: 'IE', name_pt: 'Irlanda', name_es: 'Irlanda', name_en: 'Ireland', dial: '+353', flag: '🇮🇪', currency: 'EUR', mask: 'XX XXX XXXX', digits: 10, pix: false },
  { code: 'IL', name_pt: 'Israel', name_es: 'Israel', name_en: 'Israel', dial: '+972', flag: '🇮🇱', currency: 'ILS', mask: 'XX XXX XXXX', digits: 12, pix: false },
  { code: 'IM', name_pt: 'Ilha de Man', name_es: 'Isla de Man', name_en: 'Isle of Man', dial: '+44', flag: '🇮🇲', currency: 'GBP', mask: 'XXXX XXXXXX', digits: 10, pix: false },
  { code: 'IN', name_pt: 'Índia', name_es: 'India', name_en: 'India', dial: '+91', flag: '🇮🇳', currency: 'INR', mask: 'XXXXX XXXXX', digits: 13, pix: false },
  { code: 'IO', name_pt: 'Território Britânico do Oceano Índico', name_es: 'Territorio Británico del Océano Índico', name_en: 'British Indian Ocean Territory', dial: '+246', flag: '🇮🇴', currency: 'USD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'IQ', name_pt: 'Iraque', name_es: 'Irak', name_en: 'Iraq', dial: '+964', flag: '🇮🇶', currency: 'IQD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'IR', name_pt: 'Irã', name_es: 'Irán', name_en: 'Iran', dial: '+98', flag: '🇮🇷', currency: 'IRR', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'IS', name_pt: 'Islândia', name_es: 'Islandia', name_en: 'Iceland', dial: '+354', flag: '🇮🇸', currency: 'ISK', mask: 'XXX XXXX', digits: 9, pix: false },
  { code: 'IT', name_pt: 'Itália', name_es: 'Italia', name_en: 'Italy', dial: '+39', flag: '🇮🇹', currency: 'EUR', mask: 'XXX XXX XXXX', digits: 12, pix: false },
  { code: 'JE', name_pt: 'Jersey', name_es: 'Jersey', name_en: 'Jersey', dial: '+44', flag: '🇯🇪', currency: 'GBP', mask: 'XXXX XXXXXX', digits: 10, pix: false },
  { code: 'JM', name_pt: 'Jamaica', name_es: 'Jamaica', name_en: 'Jamaica', dial: '+1', flag: '🇯🇲', currency: 'JMD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'JO', name_pt: 'Jordânia', name_es: 'Jordania', name_en: 'Jordan', dial: '+962', flag: '🇯🇴', currency: 'JOD', mask: 'X XXXX XXXX', digits: 9, pix: false },
  { code: 'JP', name_pt: 'Japão', name_es: 'Japón', name_en: 'Japan', dial: '+81', flag: '🇯🇵', currency: 'JPY', mask: 'XX XXXX XXXX', digits: 15, pix: false },
  { code: 'KE', name_pt: 'Quênia', name_es: 'Kenia', name_en: 'Kenya', dial: '+254', flag: '🇰🇪', currency: 'KES', mask: 'XXX XXXXXX', digits: 10, pix: false },
  { code: 'KG', name_pt: 'Quirguistão', name_es: 'Kirguistán', name_en: 'Kyrgyzstan', dial: '+996', flag: '🇰🇬', currency: 'KGS', mask: 'XXX XXX XXX', digits: 10, pix: false },
  { code: 'KH', name_pt: 'Camboja', name_es: 'Camboya', name_en: 'Cambodia', dial: '+855', flag: '🇰🇭', currency: 'KHR', mask: 'XX XXX XXX', digits: 10, pix: false },
  { code: 'KI', name_pt: 'Quiribati', name_es: 'Kiribati', name_en: 'Kiribati', dial: '+686', flag: '🇰🇮', currency: 'AUD', mask: 'XXXXXXXX', digits: 8, pix: false },
  { code: 'KM', name_pt: 'Comores', name_es: 'Comoras', name_en: 'Comoros', dial: '+269', flag: '🇰🇲', currency: 'KMF', mask: 'XXX XX XX', digits: 7, pix: false },
  { code: 'KN', name_pt: 'São Cristóvão e Névis', name_es: 'San Cristóbal y Nieves', name_en: 'St. Kitts & Nevis', dial: '+1', flag: '🇰🇳', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'KP', name_pt: 'Coreia do Norte', name_es: 'Corea del Norte', name_en: 'North Korea', dial: '+850', flag: '🇰🇵', currency: 'KPW', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'KR', name_pt: 'Coreia do Sul', name_es: 'Corea del Sur', name_en: 'South Korea', dial: '+82', flag: '🇰🇷', currency: 'KRW', mask: 'XX XXXX XXXX', digits: 14, pix: false },
  { code: 'KW', name_pt: 'Kuwait', name_es: 'Kuwait', name_en: 'Kuwait', dial: '+965', flag: '🇰🇼', currency: 'KWD', mask: 'XXX XXXXX', digits: 8, pix: false },
  { code: 'KY', name_pt: 'Ilhas Cayman', name_es: 'Islas Caimán', name_en: 'Cayman Islands', dial: '+1', flag: '🇰🇾', currency: 'KYD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'KZ', name_pt: 'Cazaquistão', name_es: 'Kazajistán', name_en: 'Kazakhstan', dial: '+7', flag: '🇰🇿', currency: 'KZT', mask: 'X XXX XXX XXXX', digits: 14, pix: false },
  { code: 'LA', name_pt: 'Laos', name_es: 'Laos', name_en: 'Laos', dial: '+856', flag: '🇱🇦', currency: 'LAK', mask: 'XX XX XXX XXX', digits: 10, pix: false },
  { code: 'LB', name_pt: 'Líbano', name_es: 'Líbano', name_en: 'Lebanon', dial: '+961', flag: '🇱🇧', currency: 'LBP', mask: 'XX XXX XXX', digits: 8, pix: false },
  { code: 'LC', name_pt: 'Santa Lúcia', name_es: 'Santa Lucía', name_en: 'St. Lucia', dial: '+1', flag: '🇱🇨', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'LI', name_pt: 'Liechtenstein', name_es: 'Liechtenstein', name_en: 'Liechtenstein', dial: '+423', flag: '🇱🇮', currency: 'CHF', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'LK', name_pt: 'Sri Lanka', name_es: 'Sri Lanka', name_en: 'Sri Lanka', dial: '+94', flag: '🇱🇰', currency: 'LKR', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'LR', name_pt: 'Libéria', name_es: 'Liberia', name_en: 'Liberia', dial: '+231', flag: '🇱🇷', currency: 'LRD', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'LS', name_pt: 'Lesoto', name_es: 'Lesoto', name_en: 'Lesotho', dial: '+266', flag: '🇱🇸', currency: 'LSL', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'LT', name_pt: 'Lituânia', name_es: 'Lituania', name_en: 'Lithuania', dial: '+370', flag: '🇱🇹', currency: 'EUR', mask: 'X XXX XXXXX', digits: 8, pix: false },
  { code: 'LU', name_pt: 'Luxemburgo', name_es: 'Luxemburgo', name_en: 'Luxembourg', dial: '+352', flag: '🇱🇺', currency: 'EUR', mask: 'XXX XXX XXX', digits: 11, pix: false },
  { code: 'LV', name_pt: 'Letônia', name_es: 'Letonia', name_en: 'Latvia', dial: '+371', flag: '🇱🇻', currency: 'EUR', mask: 'XX XXX XXX', digits: 8, pix: false },
  { code: 'LY', name_pt: 'Líbia', name_es: 'Libia', name_en: 'Libya', dial: '+218', flag: '🇱🇾', currency: 'LYD', mask: 'XX XXXXXXX', digits: 9, pix: false },
  { code: 'MA', name_pt: 'Marrocos', name_es: 'Marruecos', name_en: 'Morocco', dial: '+212', flag: '🇲🇦', currency: 'MAD', mask: 'X XX XX XX XX', digits: 9, pix: false },
  { code: 'MC', name_pt: 'Mônaco', name_es: 'Mónaco', name_en: 'Monaco', dial: '+377', flag: '🇲🇨', currency: 'EUR', mask: 'X XX XX XX XX', digits: 9, pix: false },
  { code: 'MD', name_pt: 'Moldávia', name_es: 'Moldavia', name_en: 'Moldova', dial: '+373', flag: '🇲🇩', currency: 'MDL', mask: 'XXX XX XXX', digits: 8, pix: false },
  { code: 'ME', name_pt: 'Montenegro', name_es: 'Montenegro', name_en: 'Montenegro', dial: '+382', flag: '🇲🇪', currency: 'EUR', mask: 'XX XXX XXX', digits: 9, pix: false },
  { code: 'MF', name_pt: 'São Martinho', name_es: 'San Martín', name_en: 'St. Martin', dial: '+590', flag: '🇲🇫', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'MG', name_pt: 'Madagascar', name_es: 'Madagascar', name_en: 'Madagascar', dial: '+261', flag: '🇲🇬', currency: 'MGA', mask: 'XX XX XXX XX', digits: 9, pix: false },
  { code: 'MH', name_pt: 'Ilhas Marshall', name_es: 'Islas Marshall', name_en: 'Marshall Islands', dial: '+692', flag: '🇲🇭', currency: 'USD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'MK', name_pt: 'Macedônia do Norte', name_es: 'Macedonia del Norte', name_en: 'North Macedonia', dial: '+389', flag: '🇲🇰', currency: 'MKD', mask: 'XX XXX XXX', digits: 8, pix: false },
  { code: 'ML', name_pt: 'Mali', name_es: 'Mali', name_en: 'Mali', dial: '+223', flag: '🇲🇱', currency: 'XOF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'MM', name_pt: 'Mianmar (Birmânia)', name_es: 'Myanmar (Birmania)', name_en: 'Myanmar (Burma)', dial: '+95', flag: '🇲🇲', currency: 'MMK', mask: 'X XXX XXXX', digits: 10, pix: false },
  { code: 'MN', name_pt: 'Mongólia', name_es: 'Mongolia', name_en: 'Mongolia', dial: '+976', flag: '🇲🇳', currency: 'MNT', mask: 'XXXX XXXX', digits: 10, pix: false },
  { code: 'MO', name_pt: 'Macau, RAE da China', name_es: 'RAE de Macao (China)', name_en: 'Macao SAR China', dial: '+853', flag: '🇲🇴', currency: 'MOP', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'MP', name_pt: 'Ilhas Marianas do Norte', name_es: 'Islas Marianas del Norte', name_en: 'Northern Mariana Islands', dial: '+1', flag: '🇲🇵', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'MQ', name_pt: 'Martinica', name_es: 'Martinica', name_en: 'Martinique', dial: '+596', flag: '🇲🇶', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'MR', name_pt: 'Mauritânia', name_es: 'Mauritania', name_en: 'Mauritania', dial: '+222', flag: '🇲🇷', currency: 'MRU', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'MS', name_pt: 'Montserrat', name_es: 'Montserrat', name_en: 'Montserrat', dial: '+1', flag: '🇲🇸', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'MT', name_pt: 'Malta', name_es: 'Malta', name_en: 'Malta', dial: '+356', flag: '🇲🇹', currency: 'EUR', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'MU', name_pt: 'Maurício', name_es: 'Mauricio', name_en: 'Mauritius', dial: '+230', flag: '🇲🇺', currency: 'MUR', mask: 'XXXX XXXX', digits: 10, pix: false },
  { code: 'MV', name_pt: 'Maldivas', name_es: 'Maldivas', name_en: 'Maldives', dial: '+960', flag: '🇲🇻', currency: 'MVR', mask: 'XXX XXXX', digits: 10, pix: false },
  { code: 'MW', name_pt: 'Malaui', name_es: 'Malaui', name_en: 'Malawi', dial: '+265', flag: '🇲🇼', currency: 'MWK', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'MX', name_pt: 'México', name_es: 'México', name_en: 'Mexico', dial: '+52', flag: '🇲🇽', lang: 'es', currency: 'MXN', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'MY', name_pt: 'Malásia', name_es: 'Malasia', name_en: 'Malaysia', dial: '+60', flag: '🇲🇾', currency: 'MYR', mask: 'XX XXX XXXX', digits: 10, pix: false },
  { code: 'MZ', name_pt: 'Moçambique', name_es: 'Mozambique', name_en: 'Mozambique', dial: '+258', flag: '🇲🇿', lang: 'pt', currency: 'MZN', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'NA', name_pt: 'Namíbia', name_es: 'Namibia', name_en: 'Namibia', dial: '+264', flag: '🇳🇦', currency: 'NAD', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'NC', name_pt: 'Nova Caledônia', name_es: 'Nueva Caledonia', name_en: 'New Caledonia', dial: '+687', flag: '🇳🇨', currency: 'XPF', mask: 'XX.XX.XX', digits: 6, pix: false },
  { code: 'NE', name_pt: 'Níger', name_es: 'Níger', name_en: 'Niger', dial: '+227', flag: '🇳🇪', currency: 'XOF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'NF', name_pt: 'Ilha Norfolk', name_es: 'Isla Norfolk', name_en: 'Norfolk Island', dial: '+672', flag: '🇳🇫', currency: 'AUD', mask: 'X XXXXX', digits: 6, pix: false },
  { code: 'NG', name_pt: 'Nigéria', name_es: 'Nigeria', name_en: 'Nigeria', dial: '+234', flag: '🇳🇬', currency: 'NGN', mask: 'XXX XXX XXXX', digits: 14, pix: false },
  { code: 'NI', name_pt: 'Nicarágua', name_es: 'Nicaragua', name_en: 'Nicaragua', dial: '+505', flag: '🇳🇮', lang: 'es', currency: 'NIO', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'NL', name_pt: 'Países Baixos', name_es: 'Países Bajos', name_en: 'Netherlands', dial: '+31', flag: '🇳🇱', currency: 'EUR', mask: 'X XXXXXXXX', digits: 11, pix: false },
  { code: 'NO', name_pt: 'Noruega', name_es: 'Noruega', name_en: 'Norway', dial: '+47', flag: '🇳🇴', currency: 'NOK', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'NP', name_pt: 'Nepal', name_es: 'Nepal', name_en: 'Nepal', dial: '+977', flag: '🇳🇵', currency: 'NPR', mask: 'XXX XXXXXXX', digits: 11, pix: false },
  { code: 'NR', name_pt: 'Nauru', name_es: 'Nauru', name_en: 'Nauru', dial: '+674', flag: '🇳🇷', currency: 'AUD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'NU', name_pt: 'Niue', name_es: 'Niue', name_en: 'Niue', dial: '+683', flag: '🇳🇺', currency: 'NZD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'NZ', name_pt: 'Nova Zelândia', name_es: 'Nueva Zelanda', name_en: 'New Zealand', dial: '+64', flag: '🇳🇿', currency: 'NZD', mask: 'XX XXX XXXX', digits: 10, pix: false },
  { code: 'OM', name_pt: 'Omã', name_es: 'Omán', name_en: 'Oman', dial: '+968', flag: '🇴🇲', currency: 'OMR', mask: 'XXXX XXXX', digits: 9, pix: false },
  { code: 'PA', name_pt: 'Panamá', name_es: 'Panamá', name_en: 'Panama', dial: '+507', flag: '🇵🇦', lang: 'es', currency: 'PAB', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'PF', name_pt: 'Polinésia Francesa', name_es: 'Polinesia Francesa', name_en: 'French Polynesia', dial: '+689', flag: '🇵🇫', currency: 'XPF', mask: 'XX XX XX XX', digits: 9, pix: false },
  { code: 'PG', name_pt: 'Papua-Nova Guiné', name_es: 'Papúa Nueva Guinea', name_en: 'Papua New Guinea', dial: '+675', flag: '🇵🇬', currency: 'PGK', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'PH', name_pt: 'Filipinas', name_es: 'Filipinas', name_en: 'Philippines', dial: '+63', flag: '🇵🇭', currency: 'PHP', mask: 'XXX XXX XXXX', digits: 13, pix: false },
  { code: 'PK', name_pt: 'Paquistão', name_es: 'Pakistán', name_en: 'Pakistan', dial: '+92', flag: '🇵🇰', currency: 'PKR', mask: 'XXX XXXXXXX', digits: 12, pix: false },
  { code: 'PL', name_pt: 'Polônia', name_es: 'Polonia', name_en: 'Poland', dial: '+48', flag: '🇵🇱', currency: 'PLN', mask: 'XXX XXX XXX', digits: 10, pix: false },
  { code: 'PM', name_pt: 'São Pedro e Miquelão', name_es: 'San Pedro y Miquelón', name_en: 'St. Pierre & Miquelon', dial: '+508', flag: '🇵🇲', currency: 'EUR', mask: 'XX XX XX', digits: 9, pix: false },
  { code: 'PR', name_pt: 'Porto Rico', name_es: 'Puerto Rico', name_en: 'Puerto Rico', dial: '+1', flag: '🇵🇷', lang: 'es', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'PS', name_pt: 'Territórios palestinos', name_es: 'Territorios Palestinos', name_en: 'Palestinian Territories', dial: '+970', flag: '🇵🇸', currency: 'ILS', mask: 'XXX XXX XXX', digits: 10, pix: false },
  { code: 'PW', name_pt: 'Palau', name_es: 'Palaos', name_en: 'Palau', dial: '+680', flag: '🇵🇼', currency: 'USD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'QA', name_pt: 'Catar', name_es: 'Catar', name_en: 'Qatar', dial: '+974', flag: '🇶🇦', currency: 'QAR', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'RE', name_pt: 'Reunião', name_es: 'Reunión', name_en: 'Réunion', dial: '+262', flag: '🇷🇪', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'RO', name_pt: 'Romênia', name_es: 'Rumania', name_en: 'Romania', dial: '+40', flag: '🇷🇴', currency: 'RON', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'RS', name_pt: 'Sérvia', name_es: 'Serbia', name_en: 'Serbia', dial: '+381', flag: '🇷🇸', currency: 'RSD', mask: 'XX XXXXXXX', digits: 12, pix: false },
  { code: 'RU', name_pt: 'Rússia', name_es: 'Rusia', name_en: 'Russia', dial: '+7', flag: '🇷🇺', currency: 'RUB', mask: 'X XXX XXX XX XX', digits: 14, pix: false },
  { code: 'RW', name_pt: 'Ruanda', name_es: 'Ruanda', name_en: 'Rwanda', dial: '+250', flag: '🇷🇼', currency: 'RWF', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'SA', name_pt: 'Arábia Saudita', name_es: 'Arabia Saudita', name_en: 'Saudi Arabia', dial: '+966', flag: '🇸🇦', currency: 'SAR', mask: 'XX XXX XXXX', digits: 10, pix: false },
  { code: 'SB', name_pt: 'Ilhas Salomão', name_es: 'Islas Salomón', name_en: 'Solomon Islands', dial: '+677', flag: '🇸🇧', currency: 'SBD', mask: 'XX XXXXX', digits: 7, pix: false },
  { code: 'SC', name_pt: 'Seicheles', name_es: 'Seychelles', name_en: 'Seychelles', dial: '+248', flag: '🇸🇨', currency: 'SCR', mask: 'X XXX XXX', digits: 7, pix: false },
  { code: 'SD', name_pt: 'Sudão', name_es: 'Sudán', name_en: 'Sudan', dial: '+249', flag: '🇸🇩', currency: 'SDG', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'SE', name_pt: 'Suécia', name_es: 'Suecia', name_en: 'Sweden', dial: '+46', flag: '🇸🇪', currency: 'SEK', mask: 'XX XXX XX XX', digits: 12, pix: false },
  { code: 'SG', name_pt: 'Singapura', name_es: 'Singapur', name_en: 'Singapore', dial: '+65', flag: '🇸🇬', currency: 'SGD', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'SH', name_pt: 'Santa Helena', name_es: 'Santa Elena', name_en: 'St. Helena', dial: '+290', flag: '🇸🇭', currency: 'SHP', mask: 'XXXXX', digits: 5, pix: false },
  { code: 'SI', name_pt: 'Eslovênia', name_es: 'Eslovenia', name_en: 'Slovenia', dial: '+386', flag: '🇸🇮', currency: 'EUR', mask: 'XX XXX XXX', digits: 8, pix: false },
  { code: 'SJ', name_pt: 'Svalbard e Jan Mayen', name_es: 'Svalbard y Jan Mayen', name_en: 'Svalbard & Jan Mayen', dial: '+47', flag: '🇸🇯', currency: 'NOK', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'SK', name_pt: 'Eslováquia', name_es: 'Eslovaquia', name_en: 'Slovakia', dial: '+421', flag: '🇸🇰', currency: 'EUR', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'SL', name_pt: 'Serra Leoa', name_es: 'Sierra Leona', name_en: 'Sierra Leone', dial: '+232', flag: '🇸🇱', currency: 'SLE', mask: 'XXX XXXXXX', digits: 8, pix: false },
  { code: 'SM', name_pt: 'San Marino', name_es: 'San Marino', name_en: 'San Marino', dial: '+378', flag: '🇸🇲', currency: 'EUR', mask: 'XX XX XX XX', digits: 10, pix: false },
  { code: 'SN', name_pt: 'Senegal', name_es: 'Senegal', name_en: 'Senegal', dial: '+221', flag: '🇸🇳', currency: 'XOF', mask: 'XX XXX XX XX', digits: 9, pix: false },
  { code: 'SO', name_pt: 'Somália', name_es: 'Somalia', name_en: 'Somalia', dial: '+252', flag: '🇸🇴', currency: 'SOS', mask: 'X XXXXXXX', digits: 9, pix: false },
  { code: 'SR', name_pt: 'Suriname', name_es: 'Surinam', name_en: 'Suriname', dial: '+597', flag: '🇸🇷', currency: 'SRD', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'SS', name_pt: 'Sudão do Sul', name_es: 'Sudán del Sur', name_en: 'South Sudan', dial: '+211', flag: '🇸🇸', currency: 'SSP', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'ST', name_pt: 'São Tomé e Príncipe', name_es: 'Santo Tomé y Príncipe', name_en: 'São Tomé & Príncipe', dial: '+239', flag: '🇸🇹', lang: 'pt', currency: 'STN', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'SV', name_pt: 'El Salvador', name_es: 'El Salvador', name_en: 'El Salvador', dial: '+503', flag: '🇸🇻', lang: 'es', currency: 'USD', mask: 'XXXX XXXX', digits: 11, pix: false },
  { code: 'SX', name_pt: 'Sint Maarten', name_es: 'Sint Maarten', name_en: 'Sint Maarten', dial: '+1', flag: '🇸🇽', currency: 'XCG', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'SY', name_pt: 'Síria', name_es: 'Siria', name_en: 'Syria', dial: '+963', flag: '🇸🇾', currency: 'SYP', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'SZ', name_pt: 'Essuatíni', name_es: 'Esuatini', name_en: 'Eswatini', dial: '+268', flag: '🇸🇿', currency: 'SZL', mask: 'XXXX XXXX', digits: 9, pix: false },
  { code: 'TC', name_pt: 'Ilhas Turcas e Caicos', name_es: 'Islas Turcas y Caicos', name_en: 'Turks & Caicos Islands', dial: '+1', flag: '🇹🇨', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'TD', name_pt: 'Chade', name_es: 'Chad', name_en: 'Chad', dial: '+235', flag: '🇹🇩', currency: 'XAF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'TG', name_pt: 'Togo', name_es: 'Togo', name_en: 'Togo', dial: '+228', flag: '🇹🇬', currency: 'XOF', mask: 'XX XX XX XX', digits: 8, pix: false },
  { code: 'TH', name_pt: 'Tailândia', name_es: 'Tailandia', name_en: 'Thailand', dial: '+66', flag: '🇹🇭', currency: 'THB', mask: 'XX XXX XXXX', digits: 13, pix: false },
  { code: 'TJ', name_pt: 'Tadjiquistão', name_es: 'Tayikistán', name_en: 'Tajikistan', dial: '+992', flag: '🇹🇯', currency: 'TJS', mask: 'XX XXX XXXX', digits: 9, pix: false },
  { code: 'TK', name_pt: 'Tokelau', name_es: 'Tokelau', name_en: 'Tokelau', dial: '+690', flag: '🇹🇰', currency: 'NZD', mask: 'XXXX', digits: 7, pix: false },
  { code: 'TL', name_pt: 'Timor-Leste', name_es: 'Timor Oriental', name_en: 'Timor-Leste', dial: '+670', flag: '🇹🇱', lang: 'pt', currency: 'USD', mask: 'XXXX XXXX', digits: 8, pix: false },
  { code: 'TM', name_pt: 'Turcomenistão', name_es: 'Turkmenistán', name_en: 'Turkmenistan', dial: '+993', flag: '🇹🇲', currency: 'TMT', mask: 'X XX XXXXXX', digits: 8, pix: false },
  { code: 'TN', name_pt: 'Tunísia', name_es: 'Túnez', name_en: 'Tunisia', dial: '+216', flag: '🇹🇳', currency: 'TND', mask: 'XX XXX XXX', digits: 8, pix: false },
  { code: 'TO', name_pt: 'Tonga', name_es: 'Tonga', name_en: 'Tonga', dial: '+676', flag: '🇹🇴', currency: 'TOP', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'TR', name_pt: 'Turquia', name_es: 'Turquía', name_en: 'Türkiye', dial: '+90', flag: '🇹🇷', currency: 'TRY', mask: 'XXX XXX XX XX', digits: 13, pix: false },
  { code: 'TT', name_pt: 'Trinidad e Tobago', name_es: 'Trinidad y Tobago', name_en: 'Trinidad & Tobago', dial: '+1', flag: '🇹🇹', currency: 'TTD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'TV', name_pt: 'Tuvalu', name_es: 'Tuvalu', name_en: 'Tuvalu', dial: '+688', flag: '🇹🇻', currency: 'AUD', mask: 'XX XXXX', digits: 7, pix: false },
  { code: 'TW', name_pt: 'Taiwan', name_es: 'Taiwán', name_en: 'Taiwan', dial: '+886', flag: '🇹🇼', currency: 'TWD', mask: 'XXX XXX XXX', digits: 11, pix: false },
  { code: 'TZ', name_pt: 'Tanzânia', name_es: 'Tanzania', name_en: 'Tanzania', dial: '+255', flag: '🇹🇿', currency: 'TZS', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'UA', name_pt: 'Ucrânia', name_es: 'Ucrania', name_en: 'Ukraine', dial: '+380', flag: '🇺🇦', currency: 'UAH', mask: 'XX XXX XXXX', digits: 10, pix: false },
  { code: 'UG', name_pt: 'Uganda', name_es: 'Uganda', name_en: 'Uganda', dial: '+256', flag: '🇺🇬', currency: 'UGX', mask: 'XXX XXXXXX', digits: 9, pix: false },
  { code: 'US', name_pt: 'Estados Unidos', name_es: 'Estados Unidos', name_en: 'United States', dial: '+1', flag: '🇺🇸', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'UZ', name_pt: 'Uzbequistão', name_es: 'Uzbekistán', name_en: 'Uzbekistan', dial: '+998', flag: '🇺🇿', currency: 'UZS', mask: 'XX XXX XX XX', digits: 9, pix: false },
  { code: 'VA', name_pt: 'Cidade do Vaticano', name_es: 'Ciudad del Vaticano', name_en: 'Vatican City', dial: '+39', flag: '🇻🇦', currency: 'EUR', mask: 'XXX XXX XXXX', digits: 12, pix: false },
  { code: 'VC', name_pt: 'São Vicente e Granadinas', name_es: 'San Vicente y las Granadinas', name_en: 'St. Vincent & Grenadines', dial: '+1', flag: '🇻🇨', currency: 'XCD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'VG', name_pt: 'Ilhas Virgens Britânicas', name_es: 'Islas Vírgenes Británicas', name_en: 'British Virgin Islands', dial: '+1', flag: '🇻🇬', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'VI', name_pt: 'Ilhas Virgens Americanas', name_es: 'Islas Vírgenes de EE. UU.', name_en: 'U.S. Virgin Islands', dial: '+1', flag: '🇻🇮', currency: 'USD', mask: 'XXX XXX XXXX', digits: 10, pix: false },
  { code: 'VN', name_pt: 'Vietnã', name_es: 'Vietnam', name_en: 'Vietnam', dial: '+84', flag: '🇻🇳', currency: 'VND', mask: 'XXX XXX XXX', digits: 10, pix: false },
  { code: 'VU', name_pt: 'Vanuatu', name_es: 'Vanuatu', name_en: 'Vanuatu', dial: '+678', flag: '🇻🇺', currency: 'VUV', mask: 'XXX XXXX', digits: 7, pix: false },
  { code: 'WF', name_pt: 'Wallis e Futuna', name_es: 'Wallis y Futuna', name_en: 'Wallis & Futuna', dial: '+681', flag: '🇼🇫', currency: 'XPF', mask: 'XX XX XX', digits: 9, pix: false },
  { code: 'WS', name_pt: 'Samoa', name_es: 'Samoa', name_en: 'Samoa', dial: '+685', flag: '🇼🇸', currency: 'WST', mask: 'XX XXXXX', digits: 10, pix: false },
  { code: 'XK', name_pt: 'Kosovo', name_es: 'Kosovo', name_en: 'Kosovo', dial: '+383', flag: '🇽🇰', currency: 'EUR', mask: 'XX XXX XXX', digits: 12, pix: false },
  { code: 'YE', name_pt: 'Iêmen', name_es: 'Yemen', name_en: 'Yemen', dial: '+967', flag: '🇾🇪', currency: 'YER', mask: 'XXX XXX XXX', digits: 9, pix: false },
  { code: 'YT', name_pt: 'Mayotte', name_es: 'Mayotte', name_en: 'Mayotte', dial: '+262', flag: '🇾🇹', currency: 'EUR', mask: 'XXX XX XX XX', digits: 9, pix: false },
  { code: 'ZA', name_pt: 'África do Sul', name_es: 'Sudáfrica', name_en: 'South Africa', dial: '+27', flag: '🇿🇦', currency: 'ZAR', mask: 'XX XXX XXXX', digits: 10, pix: false },
  { code: 'ZM', name_pt: 'Zâmbia', name_es: 'Zambia', name_en: 'Zambia', dial: '+260', flag: '🇿🇲', currency: 'ZMW', mask: 'XX XXXXXXX', digits: 9, pix: false },
  { code: 'ZW', name_pt: 'Zimbábue', name_es: 'Zimbabue', name_en: 'Zimbabwe', dial: '+263', flag: '🇿🇼', currency: 'ZWG', mask: 'XX XXX XXXX', digits: 10, pix: false },
]

const POR_CODIGO = new Map(COUNTRIES.map((c) => [c.code, c]))

export function countryByCode(code: string) {
  return POR_CODIGO.get(code)
}

/** Países ordenados por nombre en el idioma de la app, filtrados por nombre o prefijo. */
export function buscarPaises(lang: string, q = '') {
  const limpio = (x: string) => x.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
  const b = limpio(q.trim())
  const num = b.replace(/\D/g, '')
  return COUNTRIES
    .filter((c) => !b || limpio(nombrePais(c, lang)).includes(b) || (!!num && c.dial.includes(num)))
    .sort((x, y) => nombrePais(x, lang).localeCompare(nombrePais(y, lang), lang))
}

/** Nombre del país en el idioma de la app. */
export function nombrePais(c: Pick<Country, 'name_pt' | 'name_es' | 'name_en'>, lang: string) {
  return lang.startsWith('es') ? c.name_es : lang.startsWith('en') ? c.name_en : c.name_pt
}
