// Texto legal extraido automaticamente de https://rutyn.com.br/politica-de-privacidade/
// No editar a mano: si cambia la politica publicada, volver a extraerlo desde ahi.
// Solo existe la version en espanol; falta el texto oficial en portugues e ingles.

export type BloqueLegal = { tag: 'intro' | 'h' | 'p' | 'li'; text: string }

export const terminosEs: BloqueLegal[] = [
  { tag: 'intro', text: `CONDICIONES DE USO Y POLÍTICA DE PRIVACIDAD - RUTYN APP JONATHAN DELGADO , persona física, registrada con el CPF nº 014.249.569-78, con domicilio en la ciudad de Florianópolis, Estado de Santa Catarina, Brasil, bajo el nombre “RUTYN”, es responsable de la operación, mantenimiento y disponibilidad de la Plataforma Rutyn (“Plataforma”), accesible a través del sitio web y aplicación móvil. Este documento fue elaborado de conformidad con la Ley General de Protección de Datos Personales – LGPD (Ley 13.709/18), el Marco Civil de Internet (Ley 12.965/14) y demás normativa aplicable, formando parte integrante de los Términos y Condiciones de Uso de la Plataforma. Se recomienda consultar periódicamente este documento, ya que puede ser actualizado en caso de cambios legales u operativos.` },
  { tag: 'h', text: `1. DATOS PERSONALES RECOPILADOS` },
  { tag: 'p', text: `1.1. Rutyn, como responsable del tratamiento de datos, recopila la información proporcionada voluntariamente por los usuarios al registrarse y durante el uso de la Plataforma.` },
  { tag: 'p', text: `1.2. Los datos podrán incluir, entre otros:` },
  { tag: 'li', text: `Nombre completo` },
  { tag: 'li', text: `CPF` },
  { tag: 'li', text: `Documento de identidad` },
  { tag: 'li', text: `Fecha de nacimiento` },
  { tag: 'li', text: `Correo electrónico` },
  { tag: 'li', text: `Número de teléfono` },
  { tag: 'li', text: `Dirección` },
  { tag: 'li', text: `Datos profesionales del profesor` },
  { tag: 'li', text: `Información física y de evaluación compartida por el estudiante` },
  { tag: 'li', text: `Detalles de pago (los datos confidenciales de la tarjeta no se almacenan)` },
  { tag: 'p', text: `1.3. El usuario declara tener autorización para compartir datos con terceros dentro de la Plataforma.` },
  { tag: 'p', text: `1.4. Rutyn no recopila datos sensibles sin consentimiento específico.` },
  { tag: 'p', text: `1.5. Todos los datos deben ser reales y pertenecer a sus respectivos propietarios.` },
  { tag: 'h', text: `2. FINALIDAD DEL TRATAMIENTO DE DATOS` },
  { tag: 'p', text: `Los datos serán utilizados exclusivamente para:` },
  { tag: 'p', text: `a) Identificación y autenticación de usuarios b) Funcionamiento de entrenamientos, dietas, evaluaciones, chat y progresos c) Mejora de técnicas y análisis de uso d) Prevención del fraude e) Comunicación por correo electrónico o notificaciones f) Desarrollo y mejora de funcionalidades, incluyendo herramientas de inteligencia artificial g) Cumplimiento de obligaciones legales` },
  { tag: 'h', text: `3. ALMACENAMIENTO Y SEGURIDAD` },
  { tag: 'p', text: `3.1. Rutyn adopta medidas de seguridad técnicas y administrativas como encriptación, control de acceso y almacenamiento protegido.` },
  { tag: 'p', text: `3.2. El acceso a los datos está restringido.` },
  { tag: 'p', text: `3.3. Rutyn no garantiza que se puedan evitar por completo los incidentes externos (piratas informáticos, virus, fallos en los dispositivos de los usuarios).` },
  { tag: 'p', text: `3.4. El usuario es responsable de la confidencialidad de su contraseña y credenciales.` },
  { tag: 'h', text: `4. INTERCAMBIO DE DATOS` },
  { tag: 'p', text: `Los datos sólo se podrán compartir en los siguientes casos:` },
  { tag: 'p', text: `a) Cumplimiento de orden legal o judicial b) Contratación de servicios tecnológicos (hosting, cloud, soporte) c) Auditorías técnicas d) Utilización de datos anonimizados con fines estadísticos` },
  { tag: 'p', text: `Rutyn exigirá cláusulas de confidencialidad a los proveedores externos.` },
  { tag: 'h', text: `5. COOKIES` },
  { tag: 'p', text: `Rutyn utiliza cookies para:` },
  { tag: 'li', text: `Seguridad y autenticación` },
  { tag: 'li', text: `Personalización de la experiencia` },
  { tag: 'li', text: `Métricas de rendimiento` },
  { tag: 'li', text: `Publicidad` },
  { tag: 'p', text: `El usuario puede desactivarlas en su navegador.` },
  { tag: 'h', text: `6. DERECHOS DEL TITULAR` },
  { tag: 'p', text: `El usuario podría:` },
  { tag: 'li', text: `Acceda a sus datos` },
  { tag: 'li', text: `Solicitar corrección` },
  { tag: 'li', text: `Solicitar eliminación` },
  { tag: 'li', text: `Solicitar portabilidad` },
  { tag: 'li', text: `Revocar el consentimiento` },
  { tag: 'p', text: `Los datos podrán conservarse durante 5 años de acuerdo con la legislación aplicable.` },
  { tag: 'h', text: `7. AUTORIZACIÓN` },
  { tag: 'p', text: `Al registrarse, el usuario acepta plenamente estos Términos y Política de Privacidad.` },
  { tag: 'h', text: `8. RESPONSABILIDADES DEL USUARIO` },
  { tag: 'p', text: `8.1. Las cuentas son personales e intransferibles. 8.2. El usuario es responsable de la información que sube a la Plataforma. 8.3. El profesor es el único responsable de los entrenamientos, las dietas y las recomendaciones que envía a sus alumnos.` },
  { tag: 'h', text: `9. PLANES Y SUSCRIPCIONES` },
  { tag: 'p', text: `Rutyn ofrece planes gratuitos y de pago. Las condiciones de cancelación se informan en la Plataforma.` },
  { tag: 'h', text: `10. TRANSACCIONES` },
  { tag: 'p', text: `Rutyn no ofrece servicios de comunicación de pago entre profesores y alumnos, salvo que se indique expresamente lo contrario. En caso de fraude, la cuenta podría ser suspendida.` },
  { tag: 'h', text: `11. FUNCIONES DE INTELIGENCIA ARTIFICIAL` },
  { tag: 'p', text: `Las herramientas de IA tienen un carácter puramente asistencial.` },
  { tag: 'p', text: `Rutyn no garantiza la precisión total del contenido generado por IA. El profesor es responsable de validar cualquier sugerencia generada automáticamente.` },
  { tag: 'h', text: `12. EXENCIÓN DE RESPONSABILIDAD – SALUD PROFESIONAL Y CONTENIDO` },
  { tag: 'p', text: `12.1. Rutyn actúa exclusivamente como plataforma tecnológica para la intermediación digital entre profesores y estudiantes.` },
  { tag: 'p', text: `12.2. Rutyn no prescribe entrenamientos, prepara dietas, supervisa evaluaciones físicas ni realiza actividades profesionales de salud.` },
  { tag: 'p', text: `12.3. Cualquier prescripción o recomendación dentro de la Plataforma es responsabilidad exclusiva del profesor.` },
  { tag: 'p', text: `12.4. Rutyn no tiene relación con asesores profesionales y no supervisa el ejercicio profesional.` },
  { tag: 'p', text: `12.5. El estudiante declara comprender que la práctica de actividad física conlleva riesgos inherentes, entre ellos:` },
  { tag: 'li', text: `lesiones musculares` },
  { tag: 'li', text: `Lesiones articulares` },
  { tag: 'li', text: `Complicaciones cardiovasculares` },
  { tag: 'li', text: `Problemas derivados de condiciones médicas preexistentes` },
  { tag: 'p', text: `12.6. Rutyn no será responsable, en ningún caso, de:` },
  { tag: 'p', text: `a) Lesiones o daños físicos derivados del ejercicio b) Problemas derivados de dietas o suplementos c) Errores técnicos del profesor d) Ejercicio deficiente por parte del alumno e) Omisión de información médica por parte del alumno` },
  { tag: 'p', text: `12.7. El estudiante declara que es su responsabilidad realizar una evaluación médica antes de iniciar cualquier programa de entrenamiento.` },
  { tag: 'p', text: `12.8. Rutyn no forma parte de la relación contractual profesional entre profesor y estudiante, limitándose a facilitar la herramienta tecnológica.` },
  { tag: 'p', text: `12.9. Rutyn no es un proveedor de servicios de salud, no actúa como entrenador personal, nutricionista o asesor médico.` },
  { tag: 'h', text: `13. LIMITACIÓN DE RESPONSABILIDAD` },
  { tag: 'p', text: `Rutyn no garantiza el funcionamiento ininterrumpido.` },
  { tag: 'p', text: `En ningún caso Rutyn será responsable de:` },
  { tag: 'li', text: `Daños indirectos` },
  { tag: 'li', text: `Pérdida de beneficios` },
  { tag: 'li', text: `Pérdida de datos` },
  { tag: 'li', text: `Daños derivados del uso indebido de la Plataforma` },
  { tag: 'h', text: `14. USO POR MENORES DE EDAD` },
  { tag: 'p', text: `14.1. La Plataforma Rutyn no está destinada a menores de 18 años que no cuenten con la autorización expresa de sus padres o representantes legales.` },
  { tag: 'p', text: `14.2. En caso de que un menor utilice la Plataforma, el registro deberá realizarse bajo la supervisión y el consentimiento expreso de su padre, madre o tutor legal, quien asumirá la plena responsabilidad del uso de la cuenta.` },
  { tag: 'p', text: `14.3. El representante legal declara que:` },
  { tag: 'p', text: `a) Autoriza el tratamiento de datos personales de menores de edad de acuerdo con la legislación vigente; b) Ha informado al docente sobre cualquier condición médica preexistente del menor; c) Entiende que la práctica de actividad física implica riesgos inherentes; d) Asume la responsabilidad de supervisar al menor durante la implementación de cualquier plan de alimentación.` },
  { tag: 'p', text: `14.4. Rutyn no realiza verificación activa de la edad ni control parental sobre la realización de actividades físicas.` },
  { tag: 'p', text: `14.5. Rutyn no será responsable, en ningún caso, de:` },
  { tag: 'p', text: `a) Lesiones físicas sufridas por los menores durante la ejecución del entrenamiento; b) Problemas de salud derivados de dietas o recomendaciones nutricionales; c) Falta de supervisión adecuada por parte del tutor legal; d) Información médica omitida por el menor o su representante.` },
  { tag: 'p', text: `14.6. El representante legal exime expresamente a Rutyn de cualquier responsabilidad civil, contractual o extracontractual derivada del uso de la Plataforma por parte del menor.` },
  { tag: 'p', text: `14.7. Si se detecta un uso indebido por parte de un menor sin autorización legal, Rutyn podrá suspender o cancelar la cuenta inmediatamente.` },
  { tag: 'h', text: `15. VALIDEZ` },
  { tag: 'p', text: `El presente documento entra en vigor desde el momento en que el usuario se registra y permanecerá vigente durante todo el uso de la Plataforma.` },
  { tag: 'h', text: `16. CONTACTO` },
  { tag: 'p', text: `Para consultar el ejercicio de derechos:` },
  { tag: 'p', text: `Correo electrónico: suporte.rutyn@gmail.com Sitio web: www.rutyn.com.brWhatsApp: 5548991074102` },
]
