// Texto legal de Rutyn. Es la fuente: https://rutyn.com.br/politica-de-privacidade/ publica este mismo texto.
// Si se cambia acá, actualizar también la página de la web para que digan lo mismo.
// Solo existe la versión en español.

export type BloqueLegal = { tag: 'intro' | 'h' | 'p' | 'li'; text: string }

export const terminosEs: BloqueLegal[] = [
  { tag: 'intro', text: `CONDICIONES DE USO Y POLÍTICA DE PRIVACIDAD - RUTYN APP JONATHAN DELGADO , persona física, registrada con el CPF nº 014.249.569-78, con domicilio en la ciudad de Florianópolis, Estado de Santa Catarina, Brasil, bajo el nombre “RUTYN”, es responsable de la operación, mantenimiento y disponibilidad de la Plataforma Rutyn (“Plataforma”), accesible a través del sitio web y aplicación móvil. Este documento fue elaborado de conformidad con la Ley General de Protección de Datos Personales – LGPD (Ley 13.709/18), el Marco Civil de Internet (Ley 12.965/14) y demás normativa aplicable, formando parte integrante de los Términos y Condiciones de Uso de la Plataforma. Se recomienda consultar periódicamente este documento, ya que puede ser actualizado en caso de cambios legales u operativos. Última actualización: 29 de septiembre de 2026.` },
  { tag: 'h', text: `1. DATOS PERSONALES RECOPILADOS` },
  { tag: 'p', text: `1.1. Rutyn, como responsable del tratamiento de datos, recopila la información proporcionada voluntariamente por los usuarios al registrarse y durante el uso de la Plataforma.` },
  { tag: 'p', text: `1.2. Los datos podrán incluir, entre otros:` },
  { tag: 'li', text: `Nombre completo` },
  { tag: 'li', text: `CPF` },
  { tag: 'li', text: `Documento de identidad` },
  { tag: 'li', text: `Fecha de nacimiento` },
  { tag: 'li', text: `Correo electrónico` },
  { tag: 'li', text: `Número de teléfono` },
  { tag: 'li', text: `Dirección` },
  { tag: 'li', text: `Datos profesionales del profesor` },
  { tag: 'li', text: `Información física y de evaluación compartida por el estudiante` },
  { tag: 'li', text: `Detalles de pago (los datos confidenciales de la tarjeta no se almacenan)` },
  { tag: 'p', text: `1.3. El usuario declara tener autorización para compartir datos con terceros dentro de la Plataforma.` },
  { tag: 'p', text: `1.4. Rutyn no recopila datos sensibles sin consentimiento específico.` },
  { tag: 'p', text: `1.5. Todos los datos deben ser reales y pertenecer a sus respectivos propietarios.` },
  { tag: 'h', text: `2. FINALIDAD DEL TRATAMIENTO DE DATOS` },
  { tag: 'p', text: `Los datos serán utilizados exclusivamente para:` },
  { tag: 'p', text: `a) Identificación y autenticación de usuarios b) Funcionamiento de entrenamientos, dietas, evaluaciones, chat y progresos c) Mejora de técnicas y análisis de uso d) Prevención del fraude e) Comunicación por correo electrónico o notificaciones f) Desarrollo y mejora de funcionalidades g) Cumplimiento de obligaciones legales` },
  { tag: 'h', text: `3. ALMACENAMIENTO Y SEGURIDAD` },
  { tag: 'p', text: `3.1. Rutyn adopta medidas de seguridad técnicas y administrativas como encriptación, control de acceso y almacenamiento protegido.` },
  { tag: 'p', text: `3.2. El acceso a los datos está restringido.` },
  { tag: 'p', text: `3.3. Rutyn no garantiza que se puedan evitar por completo los incidentes externos (piratas informáticos, virus, fallos en los dispositivos de los usuarios).` },
  { tag: 'p', text: `3.4. El usuario es responsable de la confidencialidad de su contraseña y credenciales.` },
  { tag: 'h', text: `4. INTERCAMBIO DE DATOS` },
  { tag: 'p', text: `Los datos sólo se podrán compartir en los siguientes casos:` },
  { tag: 'p', text: `a) Cumplimiento de orden legal o judicial b) Contratación de servicios tecnológicos (hosting, cloud, soporte) c) Auditorías técnicas d) Utilización de datos anonimizados con fines estadísticos` },
  { tag: 'p', text: `Rutyn exigirá cláusulas de confidencialidad a los proveedores externos.` },
  { tag: 'h', text: `5. COOKIES` },
  { tag: 'p', text: `Rutyn utiliza cookies para:` },
  { tag: 'li', text: `Seguridad y autenticación` },
  { tag: 'li', text: `Personalización de la experiencia` },
  { tag: 'li', text: `Métricas de rendimiento` },
  { tag: 'li', text: `Publicidad` },
  { tag: 'p', text: `El usuario puede desactivarlas en su navegador.` },
  { tag: 'h', text: `6. DERECHOS DEL TITULAR` },
  { tag: 'p', text: `El usuario podría:` },
  { tag: 'li', text: `Acceda a sus datos` },
  { tag: 'li', text: `Solicitar corrección` },
  { tag: 'li', text: `Solicitar eliminación` },
  { tag: 'li', text: `Solicitar portabilidad` },
  { tag: 'li', text: `Revocar el consentimiento` },
  { tag: 'p', text: `Cuando una cuenta se elimina (por pedido del titular, por decisión del profesor según la sección 11 o por falta de pago según la sección 10), se borran sus datos de la Plataforma: rutinas, dietas, evaluaciones, fotos, mensajes y cobros. Solo los registros de pagos y facturación de las suscripciones podrán conservarse durante 5 años, cuando la legislación aplicable lo exija.` },
  { tag: 'h', text: `7. AUTORIZACIÓN` },
  { tag: 'p', text: `Al registrarse, el usuario acepta plenamente estos Términos y Política de Privacidad.` },
  { tag: 'h', text: `8. RESPONSABILIDADES DEL USUARIO` },
  { tag: 'p', text: `8.1. Las cuentas son personales e intransferibles. 8.2. El usuario es responsable de la información que sube a la Plataforma. 8.3. El profesor es el único responsable de los entrenamientos, las dietas y las recomendaciones que envía a sus alumnos.` },
  { tag: 'h', text: `9. PLANES, PAGOS Y SUSCRIPCIONES` },
  { tag: 'p', text: `9.1. Rutyn ofrece al profesor un plan Gratis (1 alumno), un plan Básico (precio fijo que incluye 2 alumnos más un valor por cada alumno adicional) y un plan Pro (alumnos ilimitados). Los precios vigentes se informan en la Plataforma y en el sitio web. Para los alumnos el uso de la Plataforma es gratuito.` },
  { tag: 'p', text: `9.2. Los planes de pago se cobran por mes, por adelantado, con tarjeta de crédito, a través del procesador de pagos Stripe. La suscripción se renueva automáticamente cada mes hasta que el profesor la cancele. Rutyn no almacena los datos de la tarjeta.` },
  { tag: 'p', text: `9.3. La moneda y el precio dependen del país informado en el perfil del profesor. Los precios en reales (BRL) son exclusivos para profesores de Brasil con tarjeta emitida en Brasil: si se paga un precio en reales con una tarjeta de otro país, Rutyn cancelará la suscripción y devolverá el monto cobrado. Después del primer pago, el país del perfil solo puede modificarse a través del soporte.` },
  { tag: 'p', text: `9.4. Subir de plan o aumentar la cantidad de alumnos tiene efecto inmediato y se cobra la diferencia proporcional al período en curso. Bajar de plan o reducir la cantidad de alumnos tiene efecto a partir de la siguiente renovación; el período ya pagado se mantiene con las condiciones contratadas.` },
  { tag: 'p', text: `9.5. Para bajar de plan, la cantidad de alumnos vinculados (activos y suspendidos) debe caber en el plan elegido. Si hay más alumnos de los permitidos, el profesor deberá eliminar los que sobren según la sección 11.` },
  { tag: 'p', text: `9.6. El profesor puede cancelar su suscripción en cualquier momento desde la Plataforma. La cancelación tiene efecto al final del período ya pagado; hasta entonces conserva su plan. Luego la cuenta pasa al plan Gratis y los alumnos que excedan su límite quedan suspendidos hasta que el profesor contrate un plan o los elimine.` },
  { tag: 'p', text: `9.7. Los montos de períodos ya iniciados no se reembolsan, salvo el derecho de arrepentimiento dentro de los 7 días de la primera contratación previsto en el artículo 49 del Código de Defensa del Consumidor (Ley 8.078/90), los casos del punto 9.3 y los demás previstos por la ley.` },
  { tag: 'h', text: `10. FALTA DE PAGO` },
  { tag: 'p', text: `10.1. Si el cobro de la suscripción del profesor no puede realizarse, su cuenta queda suspendida por falta de pago desde ese momento. Mientras dure la suspensión, el profesor solo puede acceder a la sección de su plan para regularizar el pago, y sus alumnos solo pueden ver la pantalla de inicio con un aviso de la suspensión.` },
  { tag: 'p', text: `10.2. Al regularizar el pago, la cuenta vuelve a funcionar con todos sus datos.` },
  { tag: 'p', text: `10.3. Si el pago no se regulariza dentro de los 60 días desde el inicio de la suspensión, Rutyn eliminará de forma definitiva la cuenta del profesor y las cuentas de todos sus alumnos, con todos sus datos. Esta eliminación no puede deshacerse.` },
  { tag: 'p', text: `10.4. El alumno declara conocer que su cuenta está vinculada a la suscripción de su profesor y que puede ser suspendida o eliminada por las causas de esta sección.` },
  { tag: 'h', text: `11. ELIMINACIÓN DE ALUMNOS POR EL PROFESOR` },
  { tag: 'p', text: `11.1. El profesor puede eliminar la cuenta de cualquiera de sus alumnos. La eliminación borra de forma definitiva la cuenta del alumno y todos sus datos en la Plataforma (rutinas, dietas, evaluaciones, fotos, mensajes y cobros) y no puede deshacerse. Antes de confirmarla, la Plataforma muestra una advertencia.` },
  { tag: 'p', text: `11.2. El alumno declara conocer esta posibilidad. Si desea conservar sus datos, puede solicitarlos antes a su profesor o a Rutyn por los canales de la sección 17.` },
  { tag: 'h', text: `12. COBROS ENTRE PROFESOR Y ALUMNO` },
  { tag: 'p', text: `12.1. El pago de las clases o mensualidades del alumno al profesor se realiza directamente entre ellos, fuera de la Plataforma (por ejemplo, PIX o transferencia). Rutyn no procesa, no recibe ni garantiza esos pagos.` },
  { tag: 'p', text: `12.2. La Plataforma solo permite registrarlos: el profesor define el monto y el vencimiento, la Plataforma genera la mensualidad de cada mes, envía recordatorios, el alumno informa cuando pagó y el profesor confirma. Cualquier desacuerdo sobre esos pagos debe resolverse entre profesor y alumno.` },
  { tag: 'p', text: `12.3. En caso de fraude, la cuenta podrá ser suspendida.` },
  { tag: 'h', text: `13. EXENCIÓN DE RESPONSABILIDAD – SALUD PROFESIONAL Y CONTENIDO` },
  { tag: 'p', text: `13.1. Rutyn actúa exclusivamente como plataforma tecnológica para la intermediación digital entre profesores y estudiantes.` },
  { tag: 'p', text: `13.2. Rutyn no prescribe entrenamientos, prepara dietas, supervisa evaluaciones físicas ni realiza actividades profesionales de salud.` },
  { tag: 'p', text: `13.3. Cualquier prescripción o recomendación dentro de la Plataforma es responsabilidad exclusiva del profesor.` },
  { tag: 'p', text: `13.4. Rutyn no tiene relación con asesores profesionales y no supervisa el ejercicio profesional.` },
  { tag: 'p', text: `13.5. El estudiante declara comprender que la práctica de actividad física conlleva riesgos inherentes, entre ellos:` },
  { tag: 'li', text: `lesiones musculares` },
  { tag: 'li', text: `Lesiones articulares` },
  { tag: 'li', text: `Complicaciones cardiovasculares` },
  { tag: 'li', text: `Problemas derivados de condiciones médicas preexistentes` },
  { tag: 'p', text: `13.6. Rutyn no será responsable, en ningún caso, de:` },
  { tag: 'p', text: `a) Lesiones o daños físicos derivados del ejercicio b) Problemas derivados de dietas o suplementos c) Errores técnicos del profesor d) Ejercicio deficiente por parte del alumno e) Omisión de información médica por parte del alumno` },
  { tag: 'p', text: `13.7. El estudiante declara que es su responsabilidad realizar una evaluación médica antes de iniciar cualquier programa de entrenamiento.` },
  { tag: 'p', text: `13.8. Rutyn no forma parte de la relación contractual profesional entre profesor y estudiante, limitándose a facilitar la herramienta tecnológica.` },
  { tag: 'p', text: `13.9. Rutyn no es un proveedor de servicios de salud, no actúa como entrenador personal, nutricionista o asesor médico.` },
  { tag: 'h', text: `14. LIMITACIÓN DE RESPONSABILIDAD` },
  { tag: 'p', text: `Rutyn no garantiza el funcionamiento ininterrumpido.` },
  { tag: 'p', text: `En ningún caso Rutyn será responsable de:` },
  { tag: 'li', text: `Daños indirectos` },
  { tag: 'li', text: `Pérdida de beneficios` },
  { tag: 'li', text: `Pérdida de datos` },
  { tag: 'li', text: `Daños derivados del uso indebido de la Plataforma` },
  { tag: 'h', text: `15. USO POR MENORES DE EDAD` },
  { tag: 'p', text: `15.1. La Plataforma Rutyn no está destinada a menores de 18 años que no cuenten con la autorización expresa de sus padres o representantes legales.` },
  { tag: 'p', text: `15.2. En caso de que un menor utilice la Plataforma, el registro deberá realizarse bajo la supervisión y el consentimiento expreso de su padre, madre o tutor legal, quien asumirá la plena responsabilidad del uso de la cuenta.` },
  { tag: 'p', text: `15.3. El representante legal declara que:` },
  { tag: 'p', text: `a) Autoriza el tratamiento de datos personales de menores de edad de acuerdo con la legislación vigente; b) Ha informado al docente sobre cualquier condición médica preexistente del menor; c) Entiende que la práctica de actividad física implica riesgos inherentes; d) Asume la responsabilidad de supervisar al menor durante la implementación de cualquier plan de alimentación.` },
  { tag: 'p', text: `15.4. Rutyn no realiza verificación activa de la edad ni control parental sobre la realización de actividades físicas.` },
  { tag: 'p', text: `15.5. Rutyn no será responsable, en ningún caso, de:` },
  { tag: 'p', text: `a) Lesiones físicas sufridas por los menores durante la ejecución del entrenamiento; b) Problemas de salud derivados de dietas o recomendaciones nutricionales; c) Falta de supervisión adecuada por parte del tutor legal; d) Información médica omitida por el menor o su representante.` },
  { tag: 'p', text: `15.6. El representante legal exime expresamente a Rutyn de cualquier responsabilidad civil, contractual o extracontractual derivada del uso de la Plataforma por parte del menor.` },
  { tag: 'p', text: `15.7. Si se detecta un uso indebido por parte de un menor sin autorización legal, Rutyn podrá suspender o cancelar la cuenta inmediatamente.` },
  { tag: 'h', text: `16. VALIDEZ` },
  { tag: 'p', text: `El presente documento entra en vigor desde el momento en que el usuario se registra y permanecerá vigente durante todo el uso de la Plataforma.` },
  { tag: 'h', text: `17. CONTACTO` },
  { tag: 'p', text: `Para consultar el ejercicio de derechos:` },
  { tag: 'p', text: `Correo electrónico: suporte.rutyn@gmail.com · Sitio web: www.rutyn.com.br · WhatsApp: +55 48 99107-4102` },
]
