-- Anamnesis en tres idiomas.
-- Las preguntas ya tenían label_pt/label_es; faltaba inglés, el nombre del modelo
-- traducido y las opciones de las preguntas de selección. La respuesta se sigue
-- guardando con el texto en portugués (options), que es la clave estable; las
-- listas options_es/options_en van en el mismo orden y solo se usan para mostrar.
alter table public.anamnesis_templates add column if not exists name_es text, add column if not exists name_en text;

update public.anamnesis_templates set name_es = 'Anamnesis básica', name_en = 'Basic anamnesis', questions = '[{"id": "q1", "type": "yesno", "label_es": "¿Tienes alguna enfermedad crónica?", "label_pt": "Você tem alguma doença crônica?", "label_en": "Do you have any chronic disease?"}, {"id": "q2", "type": "text", "label_es": "Si sí, ¿cuál?", "label_pt": "Se sim, qual?", "label_en": "If so, which one?"}, {"id": "q3", "type": "yesno", "label_es": "¿Tomas alguna medicación?", "label_pt": "Você toma alguma medicação?", "label_en": "Do you take any medication?"}, {"id": "q4", "type": "text", "label_es": "Si sí, ¿cuál?", "label_pt": "Se sim, qual?", "label_en": "If so, which one?"}, {"id": "q5", "type": "text", "label_es": "¿Alguna lesión o dolor recurrente?", "label_pt": "Alguma lesão ou dor recorrente?", "label_en": "Any injury or recurring pain?"}, {"id": "q6", "type": "select", "options": ["Sedentário", "Leve", "Moderado", "Ativo", "Muito ativo"], "label_es": "Nivel de actividad actual", "label_pt": "Nível de atividade atual", "label_en": "Current activity level", "options_es": ["Sedentario", "Leve", "Moderado", "Activo", "Muy activo"], "options_en": ["Sedentary", "Light", "Moderate", "Active", "Very active"]}, {"id": "q7", "type": "select", "options": ["Emagrecimento", "Hipertrofia", "Condicionamento", "Reabilitação", "Saúde"], "label_es": "Objetivo principal", "label_pt": "Objetivo principal", "label_en": "Main goal", "options_es": ["Adelgazamiento", "Hipertrofia", "Acondicionamiento", "Rehabilitación", "Salud"], "options_en": ["Weight loss", "Hypertrophy", "Conditioning", "Rehabilitation", "Health"]}, {"id": "q8", "type": "yesno", "label_es": "¿Fumas?", "label_pt": "Fuma?", "label_en": "Do you smoke?"}, {"id": "q9", "type": "yesno", "label_es": "¿Consumes alcohol?", "label_pt": "Consome álcool?", "label_en": "Do you drink alcohol?"}, {"id": "q10", "type": "number", "label_es": "Horas de sueño por noche", "label_pt": "Horas de sono por noite", "label_en": "Hours of sleep per night"}]'::jsonb where id = '57e58992-793e-4dd2-80a2-6726f2af999e';
update public.anamnesis_templates set name_es = 'Anamnesis deportiva', name_en = 'Sports anamnesis', questions = '[{"id": "s1", "type": "text", "label_es": "¿Practicas alguna modalidad deportiva?", "label_pt": "Pratica alguma modalidade esportiva?", "label_en": "Do you practice any sport?"}, {"id": "s2", "type": "number", "label_es": "Frecuencia semanal", "label_pt": "Frequência semanal", "label_en": "Weekly frequency"}, {"id": "s3", "type": "yesno", "label_es": "¿Ya has entrenado con pesas antes?", "label_pt": "Já treinou com peso antes?", "label_en": "Have you trained with weights before?"}, {"id": "s4", "type": "yesno", "label_es": "¿Tienes competencias en el horizonte?", "label_pt": "Tem competições no horizonte?", "label_en": "Any competitions coming up?"}, {"id": "s5", "type": "select", "options": ["Força", "Resistência", "Potência", "Todos"], "label_es": "¿Cuál es tu enfoque: fuerza, resistencia, potencia?", "label_pt": "Qual seu foco: força, resistência, potência?", "label_en": "What is your focus: strength, endurance, power?", "options_es": ["Fuerza", "Resistencia", "Potencia", "Todos"], "options_en": ["Strength", "Endurance", "Power", "All"]}]'::jsonb where id = '6cddc7b7-1624-4cfb-b808-08913d40f4a4';
